#!/bin/sh

CWD=$(pwd)
TRAMPOLINE_FILE=~/.mim/TRAMPOLINE
EXIT_CODE=0

echo "{:cwd \"$CWD\"\
       :args \"$@\"\
       :version \"1.0\"}" | nc localhost 1234

if [ -r "$TRAMPOLINE_FILE" ] && [ "$LEIN_TRAMPOLINE_WARMUP" = "" ]; then
    TRAMPOLINE="$(cat $TRAMPOLINE_FILE)"
    if [ "$INPUT_CHECKSUM" = "" ]; then
        rm $TRAMPOLINE_FILE
    fi
    exec sh -c "exec $TRAMPOLINE"
else
    exit $EXIT_CODE
fi